name: CI
on: [push]

jobs:
    build:
        runs-on: ubuntu-lastest
        steps:
            -uses: actions/checkout@v3
            -name: Set up Node.js
             uses: actions/setup-node@v3
             with:
                node-version: 18
            - run : npm install
            - run: npm test
            