name: CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        
        strategy:
          matrix:
            node-version: [16, 18, 20]
        
        steps:
            - uses: actions/checkout@v3
            - name: Set up Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}

            - name: Run with secret
              run:  echo "The secret is ${{ secrets.API_KEY }}"
            
            - name: Install dependencies
              run: |
                 if [ -f package-lock.json ]; then
                   npm ci
                 else
                   npm install
                 fi

            - name: Run tests
              run:  npm test -- --ci --watchAll=false
            
